menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/livitee
    Twitter: https://twitter.com/nobelliu
    RSS: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: nobelliu

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
